language: ruby
before_install: npm install -g grunt-cli
install: gem install github-pages
before_script: npm install
script:
  - jekyll build
  - grunt build
  - gulp build
  - diff -r _site build
  - diff -r _site export
