exclude: [src, build, node_modules, Gruntfile.js, metalsmith.json, package.json, .travis.yml]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
